[package]
name = "convert_8T_dcs_scrapper"
version = "0.1.0"
edition = "2024"
authors = ["Henrik <henrik@mertens.digital>"]
description = "Solar Power Scraper for convert 8T dcs inverters"
license-file = "LICENSE"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
scraper = "0.24.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
influxdb = { version = "0.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
toml = "0.9"

[package.metadata.deb]
maintainer = "Henrik Mertens<henrik@mertens.digital>"
copyright = "2025, Henrik Mertens<henrik@mertens.digital>"
extended-description = """
A scraper for convert 8T dcs solar inverters.
"""
depends = "$auto, systemd"
section = "utility"
priority = "optional"
assets = [
    ["target/release/convert_8T_dcs_scrapper", "usr/bin/", "755"],
    ["config.toml.example", "etc/convert_8T_dcs_scrapper/config.toml", "644"],
    ["convert_8T_dcs_scrapper.service", "lib/systemd/system/convert_8T_dcs_scrapper.service", "644"],
]
maintainer-scripts = "debian/"
systemd-units = { unit-name = "convert_8T_dcs_scrapper" }